### ISSUE TITLE
svgwrite 1.4 needs to be Python 3+

### ISSUE THREAD

**Issue by dwhswenson** [conda-forge/svgwrite-feedstock#6]
Issue:

Pretty much as said in title. The new svgwrite requires Python 3. It imports `urllib.request`, which doesn't exist in Py 2.7. I still have projects that test against 2.7, which is how I found it. Replicated in a conda env (with conda-forge in my default channels):

```
$ conda create -n svgwrite-py27 python=2.7 svgwrite
$ conda activate svgwrite-py27
$ python -c "import svgwrite"
```

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dwhs/miniconda3/envs/svgwrite-py27/lib/python2.7/site-packages/svgwrite/__init__.py", line 53, in <module>
    from svgwrite.drawing import Drawing
  File "/Users/dwhs/miniconda3/envs/svgwrite-py27/lib/python2.7/site-packages/svgwrite/drawing.py", line 29, in <module>
    from svgwrite.container import SVG, Defs
  File "/Users/dwhs/miniconda3/envs/svgwrite-py27/lib/python2.7/site-packages/svgwrite/container.py", line 26, in <module>
    from urllib.request import urlopen
ImportError: No module named request
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/dwhs/miniconda3/envs/svgwrite-py27:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
libcxx                    9.0.1                         1    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
openssl                   1.1.1e               h0b31af3_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
python                    2.7.15          h8e446fc_1011_cpython    conda-forge
python_abi                2.7                     1_cp27m    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
svgwrite                  1.4                pyh9f0ad1d_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : svgwrite-py27
    active env location : /Users/dwhs/miniconda3/envs/svgwrite-py27
            shell level : 3
       user config file : /Users/dwhs/.condarc
 populated config files : /Users/dwhs/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/dwhs/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/omnia/osx-64
                          https://conda.anaconda.org/omnia/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/dwhs/miniconda3/pkgs
                          /Users/dwhs/.conda/pkgs
       envs directories : /Users/dwhs/miniconda3/envs
                          /Users/dwhs/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

(but caught it in Linux build on Travis).

**Comment by jeromekelleher** [comment]
Thanks for the report @dwhswenson, I'll update the recipe now.

**Comment by jeromekelleher** [comment]
I've updated the recipe to remove support for older versions. However, I've realised that this may not be enough as Python 2 might still try to read the older files. We might need to remove the build 0 for this release to fix things up. Ugh.

Can you try again with the python2 env and see if it pulls in the noarch/svgwrite-1.4-pyh9f0ad1d_0.tar.bz2 package please @dwhswenson?

**Comment by dwhswenson** [comment]
Yep, Python 2 is pulling in the following:

```
svgwrite                  1.4                pyh9f0ad1d_0    conda-forge
```

Two things:

1. Looks like you're using `skip`: I think the preferred way for noarch packages now is to use `python >= 3` in host/run sections. https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python Your most recent built only did a arch'd Linux/py36 version https://anaconda.org/conda-forge/svgwrite/files (and I'm on a Mac, so I don't even see it in `conda search`)
2. Rather than removing the broken packages, I think it's just a matter of asking conda-forge to move it to the `broken` tag: https://conda-forge.org/docs/orga/guidelines.html#fixing-broken-packages

(I'll go ahead and do the latter part of that in a second comment.)

**Comment by dwhswenson** [comment]
@conda-forge/core : Could you please move the `pyh9f0ad1d_0` (and possibly `py36h9f0ad1d_1`) packages to the `broken` tag? As discussed in previous comments on this issue, missed a `python >= 3` requirement.

**Comment by beckermr** [comment]
See the cf-mark-broken repo in conda-forge

**Comment by jeromekelleher** [comment]
Ack, sorry all, I've made a mess of this. @dwhswenson, I've opened #8 which should hopefully fix the build. Once that's working we can sort out the broken builds.

Thanks for the help!

**Comment by jeromekelleher** [comment]
Huh, cf-mark-broken is cool. I'm always amazed at the level of tooling conda-forge has!

**Comment by jeromekelleher** [comment]
OK, @dwhswenson, there's a new noarch package built, so once the broken packages have been marked we should be good to go. Let's close this issue once we can confirm that Python 2 is using version 1.3 again.

**Comment by jeromekelleher** [comment]
Hi @dwhswenson, would you mind taking a look to see if the python2 install is still broken? If so I'll bump the mark-broken PR to get them pulled. Thanks for your help.

**Comment by dwhswenson** [comment]
Sorry for going AWOL, @jeromekelleher. Who knew that quarantine would have me even busier than normal! Py2.7 is definitely still trying to bring in the original build:

```
  svgwrite           conda-forge/noarch::svgwrite-1.4-pyh9f0ad1d_0
```

**Comment by jeromekelleher** [comment]
OK, the packages are marked broken so hopefully my mess is cleared up now! @dwhswenson, would you mind checking one more time please?

**Comment by dwhswenson** [comment]
Hmmm... I checked, and it is still pulling in build 0. My guess is that it may take some time to propagate through the system/various caches. The files/tags look right: https://anaconda.org/conda-forge/svgwrite/files. But I still get the wrong package locally (after cleaning out existing local copies of it) and on a re-run of a Travis job. When I run `conda search svgwrite`, I see both builds: 

```
svgwrite                         1.4            py_2  conda-forge
svgwrite                         1.4    pyh9f0ad1d_0  conda-forge
```

I'll check again later tonight and update.

**Comment by dwhswenson** [comment]
All better now! Just needed a little more time for things propagate. Thanks for taking care of this, @jeromekelleher.

**Comment by jeromekelleher** [comment]
Hooray! Thanks for your help @dwhswenson, and apologies for messing this up in the first place.
